version: 1.0.{build}
image: Visual Studio 2017

clone_folder: c:\projects\hellojava

build_script:
- cmd:
    cd c:\projects\hellojava
    mvn --version
    mvn package

artifacts:
- path: target\*.jar
  name: JAR